In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from rich.progress import track

a_temper = 'Ambient Temperature'
s_temper = 'Surface Temperature'


In [2]:
df_sum = pd.read_hdf('data_ori_na.h5','df')

# df_sum_sa = pd.read_hdf('r_data_files/data_sa_na.h5','df')

In [4]:
# time_32 = df_sum['time'].values
# time_32 = time_32/32
# time_32 = time_32.astype(int)
# df_sum['time_32'] = time_32


In [6]:
# df_sum.to_hdf('data_ori_na.h5','df')

In [6]:
# df_sum.to_hdf('r_data_files/data_ori_na.h5','df')

In [29]:
total_id_list = np.unique(df_sum['Station ID'].values)
print(total_id_list)

[  3   5   7   8   9  10  11  12  13  14  15  17  18  19  21  23  24  25
  26  27  30  31  32  33  34  35  36  37  39  40  41  42  43  44  45  46
  47  49  50  51  53  54  55  56  57  59  60  61  62  63  64  65  66  68
  69  70  71  72  73  75  76  79  80  81  82  84  85  87  88  89  92  93
  94  95  96  97  98  99 100 103 104 105 106 107 109 111 121 122]


In [93]:
total_id_list

array([  3,   5,   7,   8,   9,  10,  11,  12,  13,  14,  15,  17,  18,
        19,  21,  23,  24,  25,  26,  27,  30,  31,  32,  33,  34,  35,
        36,  37,  39,  40,  41,  42,  43,  44,  45,  46,  47,  49,  50,
        51,  53,  54,  55,  56,  57,  59,  60,  61,  62,  63,  64,  65,
        66,  68,  69,  70,  71,  72,  73,  75,  76,  79,  80,  81,  82,
        84,  85,  87,  88,  89,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 103, 104, 105, 106, 107, 109, 111, 121, 122])

In [5]:
df_sum.sort_values(by='Station ID')

Station ID    Year  Month   Day  Hour  Minute  Second  \
203026           3  2007.0    1.0  30.0  11.0    37.0     6.0   
278699           3  2007.0    3.0   1.0  15.0    52.0    26.0   
278698           3  2007.0    3.0   1.0  15.0    51.0    57.0   
278697           3  2007.0    3.0   1.0  15.0    51.0    27.0   
278696           3  2007.0    3.0   1.0  15.0    50.0    58.0   
...            ...     ...    ...   ...   ...     ...     ...   
182919         122  2007.0    2.0  27.0   4.0    46.0    14.0   
182918         122  2007.0    2.0  27.0   4.0    45.0    45.0   
182917         122  2007.0    2.0  27.0   4.0    45.0    16.0   
182923         122  2007.0    2.0  27.0   4.0    48.0    12.0   
254426         122  2007.0    3.0  24.0  12.0    13.0    37.0   

        Time since the epoch [s]  Sequence Number  Ambient Temperature  \
203026              1.170153e+09          37776.0                 5.03   
278699              1.172761e+09          29534.0                 8.42   
278698              1.172761e+09          29533.0                 8.40   
278697              1.172761e+09          29532.0                 8.39   
278696              1.172761e+09          29531.0                 8.39   
...                          ...              ...                  ...   
182919              1.172548e+09          27991.0                 3.66   
182918              1.172548e+09          27990.0                 3.61   
182917              1.172548e+09          27989.0                 3.62   
182923              1.172548e+09          27995.0                 3.56   
254426              1.174735e+09          37099.0                 4.35   

        Surface Temperature  Relative Humidity [%]      time  time_30  time_32  
203026               10.787                 73.622   7759660   258655   242489  
278699                8.350                 82.101  10366980   345566   323968  
278698                7.912                 82.691  10366951   345565   323967  
278697                8.162                 82.593  10366921   345564   323966  
278696                8.225                 82.332  10366892   345563   323965  
...                     ...                    ...       ...      ...      ...  
182919                1.413                 86.192  10154208   338473   317319  
182918                1.413                 86.135  10154179   338472   317318  
182917                1.288                 86.138  10154150   338471   317317  
182923                1.413                 86.234  10154326   338477   317322  
254426               10.662                 62.123  12341051   411368   385657  

[35444213 rows x 15 columns]

In [7]:
df_sum[df_sum['time_32']==1].sort_values(by='Station ID')

Station ID    Year  Month  Day  Hour  Minute  Second  \
1           3  2006.0   11.0  1.0  16.0    10.0     0.0   
2           3  2006.0   11.0  1.0  16.0    10.0    29.0   
1           5  2006.0   11.0  1.0  16.0    10.0     3.0   
1           8  2006.0   11.0  1.0  16.0    10.0    21.0   
1          12  2006.0   11.0  1.0  16.0    10.0    16.0   
2          13  2006.0   11.0  1.0  16.0    10.0    27.0   
1          13  2006.0   11.0  1.0  16.0     9.0    58.0   
1          14  2006.0   11.0  1.0  16.0    10.0    12.0   
1          15  2006.0   11.0  1.0  16.0    10.0    18.0   
1          17  2006.0   11.0  1.0  16.0    10.0     9.0   
2          21  2006.0   11.0  1.0  16.0    10.0    18.0   
2          23  2006.0   11.0  1.0  16.0    10.0    17.0   
2          24  2006.0   11.0  1.0  16.0    10.0    24.0   
0          25  2006.0   11.0  1.0  16.0    10.0     1.0   
1          26  2006.0   11.0  1.0  16.0    10.0    14.0   
1          35  2006.0   11.0  1.0  16.0    10.0     7.0   
1          37  2006.0   11.0  1.0  16.0    10.0    13.0   
2          39  2006.0   11.0  1.0  16.0    10.0    24.0   
0          40  2006.0   11.0  1.0  16.0    10.0    20.0   
2          41  2006.0   11.0  1.0  16.0    10.0    24.0   
1          42  2006.0   11.0  1.0  16.0    10.0     6.0   
1          43  2006.0   11.0  1.0  16.0    10.0     5.0   
1          44  2006.0   11.0  1.0  16.0    10.0    15.0   
1          45  2006.0   11.0  1.0  16.0    10.0    13.0   
1          46  2006.0   11.0  1.0  16.0    10.0     0.0   
2          46  2006.0   11.0  1.0  16.0    10.0    29.0   

   Time since the epoch [s]  Sequence Number  Ambient Temperature  \
1              1.162394e+09          13448.0                10.16   
2              1.162394e+09          13449.0                10.08   
1              1.162394e+09          59275.0                10.19   
1              1.162394e+09           3697.0                10.04   
1              1.162394e+09          44959.0                10.27   
2              1.162394e+09            302.0                10.12   
1              1.162394e+09            301.0                10.15   
1              1.162394e+09          59094.0                10.00   
1              1.162394e+09          59106.0                10.20   
1              1.162394e+09          16958.0                10.24   
2              1.162394e+09           1796.0                10.12   
2              1.162394e+09           3576.0                10.22   
2              1.162394e+09          44966.0                10.33   
0              1.162394e+09            681.0                10.29   
1              1.162394e+09          33560.0                10.03   
1              1.162394e+09           3508.0                10.22   
1              1.162394e+09           3686.0                10.10   
2              1.162394e+09             16.0                10.43   
0              1.162394e+09          23620.0                10.84   
2              1.162394e+09            148.0                10.18   
1              1.162394e+09            302.0                10.24   
1              1.162394e+09            174.0                 9.70   
1              1.162394e+09          65154.0                 9.60   
1              1.162394e+09          44455.0                10.02   
1              1.162394e+09          56097.0                10.16   
2              1.162394e+09          56098.0                10.16   

   Surface Temperature  Relative Humidity [%]  time  time_30  time_32  
1                9.100                 52.008    34        1        1  
2                9.100                 51.876    63        2        1  
1                8.662                 56.550    37        1        1  
1                9.725                 52.505    55        1        1  
1                9.975                 48.721    50        1        1  
2               10.100                 49.870    61        2        1  
1               10.287                 49

In [8]:
time_range = np.unique(df_sum['time_32'].values)
print(time_range)

[     0      1      2 ... 511067 511068 511069]


In [86]:
import pickle

In [91]:
result_array = np.ones((np.max(time_range)+1,np.max(total_id_list)+1))*(-1)
for time_id in track(time_range):
    # test_array = np.ones(np.max(total_id_list)+1)*(-1)
    result_array[time_id][total_id_list] = 0
    tmp_df = df_sum[df_sum['time_32'] == time_id]
    id_list = tmp_df['Station ID'].values
    a_temper_list = tmp_df[a_temper].values
    result_array[time_id][id_list] = a_temper_list


Working... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╺━━━━━  86% 0:20:46

FileNotFoundError: [Errno 2] No such file or directory: 'readings_timeid.pkl'

In [92]:
with open('readings_timeid2.pkl','wb') as f:
    pickle.dump(result_array,f)    

In [71]:
for id in total_id_list:
    print(id,',',result_array[1232][id])

3 , 10.12
5 , 10.2
7 , 0.0
8 , 10.0
9 , 0.0
10 , 0.0
11 , 0.0
12 , 10.24
13 , 10.26
14 , 10.02
15 , 10.19
17 , 10.14
18 , 10.02
19 , 0.0
21 , 10.12
23 , 10.23
24 , 10.34
25 , 10.26
26 , 10.02
27 , 0.0
30 , 0.0
31 , 0.0
32 , 0.0
33 , 0.0
34 , 0.0
35 , 10.21
36 , 10.22
37 , 10.1
39 , 10.42
40 , 0.0
41 , 10.16
42 , 10.16
43 , 9.72
44 , 9.6
45 , 10.04
46 , 10.12
47 , 0.0
49 , 0.0
50 , 0.0
51 , 0.0
53 , 0.0
54 , 0.0
55 , 0.0
56 , 0.0
57 , 0.0
59 , 0.0
60 , 0.0
61 , 0.0
62 , 0.0
63 , 0.0
64 , 0.0
65 , 0.0
66 , 0.0
68 , 0.0
69 , 0.0
70 , 0.0
71 , 0.0
72 , 0.0
73 , 0.0
75 , 0.0
76 , 0.0
79 , 0.0
80 , 0.0
81 , 0.0
82 , 0.0
84 , 0.0
85 , 0.0
87 , 0.0
88 , 0.0
89 , 0.0
92 , 0.0
93 , 0.0
94 , 0.0
95 , 0.0
96 , 0.0
97 , 0.0
98 , 0.0
99 , 0.0
100 , 0.0
103 , 0.0
104 , 0.0
105 , 0.0
106 , 0.0
107 , 0.0
109 , 0.0
111 , 0.0
121 , 0.0
122 , 0.0


In [54]:
len(time_range)

484405

In [55]:
np.max(time_range)

511069

In [44]:
test_array[total_id_list]

array([10.16, 10.21,  0.  , 10.02,  0.  ,  0.  ,  0.  , 10.26, 10.18,
        9.98, 10.16, 10.21, 10.02,  0.  , 10.13, 10.22, 10.35,  0.  ,
       10.03,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  , 10.24, 10.3 ,
       10.12, 10.46,  0.  , 10.17, 10.18,  9.76,  9.72, 10.02, 10.12,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ])

In [46]:
len(np.unique(id_list))

23

In [13]:
total_id_list = np.unique(df_sum['Station ID'].values)
print(total_id_list)


[  3   5   7   8   9  10  11  12  13  14  15  17  18  19  21  23  24  25
  26  27  30  31  32  33  34  35  36  37  39  40  41  42  43  44  45  46
  47  49  50  51  53  54  55  56  57  59  60  61  62  63  64  65  66  68
  69  70  71  72  73  75  76  79  80  81  82  84  85  87  88  89  92  93
  94  95  96  97  98  99 100 103 104 105 106 107 109 111 121 122]


In [21]:
test_array = np.ones(np.max(total_id_list)+1)*(-1)
print(test_array)

[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]


In [22]:
test_array[total_id_list] = 0

In [23]:
test_array[total_id_list[:4]] = 1

In [25]:
test_array[total_id_list]

array([1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [83]:
np.where(test_array == 1)

(array([], dtype=int64),)

In [85]:
df_sum[df_sum['time_32'] == 1232].sort_values(by='Station ID')

Station ID    Year  Month  Day  Hour  Minute  Second  \
1313           3  2006.0   11.0  2.0   3.0     6.0    44.0   
1298           5  2006.0   11.0  2.0   3.0     6.0    48.0   
1315           8  2006.0   11.0  2.0   3.0     6.0    36.0   
1330          12  2006.0   11.0  2.0   3.0     6.0    30.0   
1331          12  2006.0   11.0  2.0   3.0     7.0     0.0   
1324          14  2006.0   11.0  2.0   3.0     6.0    55.0   
1327          15  2006.0   11.0  2.0   3.0     6.0    33.0   
1328          17  2006.0   11.0  2.0   3.0     6.0    54.0   
1329          18  2006.0   11.0  2.0   3.0     6.0    52.0   
1548          21  2006.0   11.0  2.0   3.0     6.0    38.0   
1577          23  2006.0   11.0  2.0   3.0     6.0    37.0   
1578          23  2006.0   11.0  2.0   3.0     7.0     1.0   
1313          24  2006.0   11.0  2.0   3.0     6.0    39.0   
1323          25  2006.0   11.0  2.0   3.0     6.0    45.0   
1551          26  2006.0   11.0  2.0   3.0     6.0    57.0   
1550          26  2006.0   11.0  2.0   3.0     6.0    33.0   
794           34  2006.0   11.0  2.0   3.0     6.0    39.0   
1308          35  2006.0   11.0  2.0   3.0     6.0    50.0   
1174          36  2006.0   11.0  2.0   3.0     7.0     0.0   
1173          36  2006.0   11.0  2.0   3.0     6.0    31.0   
1315          37  2006.0   11.0  2.0   3.0     6.0    57.0   
1302          39  2006.0   11.0  2.0   3.0     6.0    43.0   
1314          41  2006.0   11.0  2.0   3.0     6.0    39.0   
1310          42  2006.0   11.0  2.0   3.0     6.0    51.0   
1320          44  2006.0   11.0  2.0   3.0     6.0    59.0   
1282          46  2006.0   11.0  2.0   3.0     6.0    44.0   

      Time since the epoch [s]  Sequence Number  Ambient Temperature  \
1313              1.162433e+09          14793.0                 3.86   
1298              1.162433e+09          60620.0                 3.42   
1315              1.162433e+09           5041.0                 3.36   
1330              1.162433e+09          46303.0                 3.33   
1331              1.162433e+09          46304.0                 3.26   
1324              1.162433e+09          60439.0                 3.91   
1327              1.162433e+09          60450.0                 3.90   
1328              1.162433e+09          18303.0                 3.62   
1329              1.162433e+09          42699.0                 3.56   
1548              1.162433e+09           3409.0                 3.75   
1577              1.162433e+09           5189.0                 4.01   
1578              1.162433e+09           5190.0                 3.96   
1313              1.162433e+09          46310.0                 4.15   
1323              1.162433e+09           2026.0                 3.72   
1551              1.162433e+09          35174.0                 3.56   
1550              1.162433e+09          35173.0                 3.56   
794               1.162433e+09           4838.0                 3.42   
1308              1.162433e+09           4853.0                 3.12   
1174              1.162433e+09           5003.0                 3.32   
1173              1.162433e+09           5002.0                 3.32   
1315              1.162433e+09           5031.0                 3.74   
1302              1.162433e+09           1324.0                 4.26   
1314              1.162433e+09           1492.0                 4.08   
1310              1.162433e+09           1647.0                 3.56   
1320              1.162433e+09            963.0                 2.84   
1282              1.162433e+09          57442.0                 3.26   

      Surface Temperature  Relative Humidity [%]   time  time_30  time_32  
1313                2.538                 72.522  39438     1314     1232  
1298                1.288                 76.695  39442     1314     1232  
1315                3.225                 72.802  39430     1314     1232  
1330                1.475                 72.517  39424     1314     1232  
1331  